[package]
name = "voidgui"
version = "0.1.0"
edition = "2021"

[lib]
name = "voidgui"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
gl = ">=0.14.0"
glfw = ">=0.51.0"
pangocairo = ">=0.17.0"
downcast-rs = ">=1.2.0"
voidmacro = { path = "../voidmacro" }
