[package]
name = "voidgui"
version = "0.1.0"
edition = "2021"

[lib]
name = "voidgui"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
gl = ">=0.14.0"
sdl2 = ">=0.35.0"
pangocairo = ">=0.17.0"
