[package]
name = "voidcrm"
version = "0.1.0"
edition = "2021"

[lib]
name = "voidcrm"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
# voidmacro = { path = "../voidmacro" }
voidgui = { path = "../voidgui" }
ciborium = ">=0.2"
serde = ">=1.0"
